### ISSUE TITLE
Killer Joe's and Vacuum Chests are working through solid blocks. 

### ISSUE THREAD

**Issue by Ayrrow** [CrazyPants/EnderIO#1560]
Pretty self explanatory, I'm not sure if this is intended behaviour or not. It's quite annoying as I have items being pulled across rooms and getting stuck on doors or the middle of floors. 

My Killer Joe's are also damaging me through the floors and walls - this in particular seems unintended as the ability to grief other people using this is high.

**Comment by hilburn** [comment]
Both are code behaving as expected - whether they should behave this way is a different matter.

Personally I would say yes it should for the vacuum chest as  every other item hoover system behaves the same way, I've had my RotaryCraft Item Vacuum pick up things from 3 chunks over...

As for the Killer Joe, maybe a config option? I think by default it would be better to leave as is - because correcting it would be relatively computationally expensive, but it would be possible to do a raytrace from the Joe to the Target and check the line of sight is clear...

**Comment by tterrag1098** [comment]
Fixed in https://github.com/hilburn/EnderIO/commit/0286245a5e81316cc0de997c25fb606703d6e7ed
