### ISSUE TITLE
[Suggestion] API Expansion?

### ISSUE THREAD

**Issue by J3FF97** [CrazyPants/EnderIO#2011]
I find it hard to find for instance the code to add new recipes to the current machines. Maybe you could expand the API a bit more to include those as well?

**Comment by 6210classick** [comment]
it's really easy just copy the recipe from the core XML then past in user XML and edit it i use Butterfly XML if you wanna see examples here is my Sagmill & Vat XML tat i added new recipes like Thermal Expansion liquids can be brewed with the vat , get saw dust from logs in the Sagmill

https://www.dropbox.com/s/xvr54gw0n1iqsoi/SAGMillRecipes_User.xml?dl=0
https://www.dropbox.com/s/901kb01l4cqciva/VatRecipes_User.xml?dl=0

there is a tiny bug i found that Enchanter User XML will not apply any enchantment books modification i don't know if adding will work but modifying any existing recipes does not seems to not work , I'm using version 2.2.8 3.4.9 / Forge 1291 i don't know if it's fixed in new version or i'm doing it wrong

**Comment by tterrag1098** [comment]
IMC.java has all you need to add recipes.

**Comment by J3FF97** [comment]
Hmm, alright, fair enough, thanks ^-^ Locked and on my way I suppose~
