### ISSUE TITLE
can't build alloy smelter in the craftingtable

### ISSUE THREAD

**Issue by Razaraf** [CrazyPants/EnderIO#2080]
I use the the world of mianite modpack with the techniclauncher.

When i put everything into the craftingtable (i tried with every copper ingot ingame) there is nothing --> no alloy smelter (even in creative mod i can't make them in the craftingtable) 

On a sidenote when i try to open the recipes it crashes (but i think thats a problem of notenoughitems)

![2015-03-12_12 42 14](https://cloud.githubusercontent.com/assets/11440053/6617090/47a31564-c8b5-11e4-9789-e7b37b45dd88.png)

**Comment by 6210classick** [comment]
what version are you using ? this seems like a very old one

**Comment by Razaraf** [comment]
If we are talking about enderio i was using enderio-1.7.10-2.2.6.317
I downloaded the newest EnderIO-1.7.10-2.2.8.349.jar but still i cant get it to work.
 I use 1.7.10 (if you want to know my minecraft version)
(Tbh i thought TechnicLauncher would auto update my mod packs :-/ )

**Comment by 6210classick** [comment]
there is a option in the config to disable recipe from Mod ingots and only use ingots from Vanilla & EIO

the current recipe in version 2.2.8 349 for Alloy Smelter is this : https://www.dropbox.com/s/chelzsvr20tzwv7/123.jpg?dl=0

if you didn't change the config file instead of iron ingot in the first recipe use copper ingot

**Comment by Razaraf** [comment]
Thank you very much. I got the wrong recipe (o.0) 
Finally i got my smelti (I even got a nick name for him)
